uploads = []

[[generated]]
id = "lWawhAOE27xVKpPICS9I5"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "tax app icon"

[[generated]]
id = "m32BrZMi52ux1R6jqDEaI"
uri = "file://attached_assets/generated_images/app_icon_for_a_92f2.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "KpH9uUhQ7kk7IZ_ynBp0u"
uri = "file://artifacts/tax-helper-video/public/images/freelancer.jpg"
type = "image"
title = "software developer freelancer working on laptop modern office space"

[[outputs]]
id = "o3YAvqQwfR4aQeHCUh6xm"
uri = "file://artifacts/tax-helper-video/public/images/farmer.jpg"
type = "image"
title = "pakistani farmer agricultural field green crops bright daylight"
